### ISSUE TITLE
Get Warehouse empty return boolean

### ISSUE THREAD

**Issue by Wabri** [DanerSound/ProgettoMP2018-2019#8]
Per convenzione metodi come questo:

https://github.com/DanerSound/ProgettoMP2018-2019/blob/e5c24c1b84e8623b7ce7da84d4871921870b3099/ProgettoMP2018-2019/src/warehouse/WareHouse.java#L37

Che ritornano un valore boolean vengono definiti con is e non get.

Il metodo dovrebbe avere la firma isWarehouseEmpty quindi.

**Comment by DanerSound** [comment]
è già stato fixato in un branch successivo a quello
