### ISSUE TITLE
Car e Gun class rifattorizzare? 

### ISSUE THREAD

**Issue by Wabri** [DanerSound/ProgettoMP2018-2019#9]
Non capisco perché car e Gun siano classi astratte e non interfacce.

Secondo me dovresti rinominarli in ICar e IGun e creare un nuovo pacchetto di interfacce all'interno di myfactory.

Tips: di solito le classi con metodi che hanno solo firme senza implementazione possono essere rifattorizzare in interfacce e se serve una implementazione ulteriore specifica viene creata una classe o un'astrazione dell'interfaccia.

**Comment by DanerSound** [comment]
![interface_interface](https://user-images.githubusercontent.com/11822185/62792246-226bd680-bacf-11e9-866a-fddb93b3de2d.png)
non possono essere delle INTERFACE perche queste gia implementano product che è una interfaccia a sua volta
